### ISSUE TITLE
Allow more times zones when retrieving data from webservices please.

### ISSUE THREAD

**Issue by cjhoard** [USGS-R/dataRetrieval#152]
I have an enhancement request, when retrieving data from waterservices using the readNWISuv command.  All of the timeseries data collected in MI is stored as EST, so when we retrieve through dataRetrieval and use "America/New_York" (the only eastern timezone allowed) as the timezone all data retrieved during daylight savings time is 1 hour off.  This poses a problem when we pull a year of data and some of the data is correct but some of the data is an hour off, so we have to do some data manipulation adjust all that. If EST were an allowed timezone it would save us some time from having to reformat the times when we retrieve the data.  Anyhow thank you for considering this enhancement request. 

for example:

    test<-readNWISuv('415318085243401',startDate="2015-06-01", endDate="2015-08-31",parameterCd = '72019',tz="America/New_York")

    head(test,1)
  agency_cd         site_no            dateTime            tz_cd X_72019_00011 X_72019_00011_cd
1      USGS 415318085243401 2015-06-01 **01:00:00** America/New_York         -0.26                P
2      USGS 415318085243401 2015-06-01 **01:15:00** America/New_York         -0.27                P

would like it to be
   agency_cd         site_no            dateTime tz_cd X_72019_00011 X_72019_00011_cd
1      USGS 415318085243401 2015-06-01 **00:00:00**   EST         -0.26                P
2      USGS 415318085243401 2015-06-01 **00:15:00**   EST         -0.27                P

**Comment by ldecicco-USGS** [comment]
I think what you are looking for is "America/Jamaica" (that is eastern timezone with no daylight savings). The timezone are base R verbiage (I would LOVE to simply use EST CDT etc, but R doesn't recognize those because they mean different things in different countries). In R, you can read the documentation on timezones like this:

```
?timezone
```

Or, have a look here:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

I will add some information to the help pages in `readNWISuv`, and add more of the options shown in the wiki link, but I think in your case, "America/Jamaica" should do the trick.

**Comment by cjhoard** [comment]
Ah I did not see that one in the tz list earlier, using that time zone code worked for us.  Thank you for the quick response and resolution.  Having that info in the help file will be useful.  Thank you again for your work on this.
