### ISSUE TITLE
Support a retry argument for service calls?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#184]
This is a question I posed for discussion. Either we expect the user to create their own retry, or we expose one. Curious what people think. Has shown up for me on stringing together WQP queries, and I wrote my own.

**Comment by ldecicco-USGS** [comment]
Put it in `getWebServiceData`? Works for me. 

I've only ever had WQP come back "improved" from a retry (so, they are doing some caching). Whereas if NWIS is down...retrys don't help. So that being said, do you think it would be better to put a retry in the general `getWebServiceData`, or in the call to `getWebServiceData` from WQP queries?

**Comment by jread-usgs** [comment]
Yeah, seems to be a bigger issue for WQP. I wrote a `retries=3` thingy, which has helped because I have gotten two fails followed by a success on a few queries.

**Comment by ldecicco-USGS** [comment]
Has the WAF issue settling down made this less of an issue? Or is it still something that happens enough that we should implement?

**Comment by jread-usgs** [comment]
Not sure. Haven't been using heavily lately, and when I do, I use my retry wrapper

**Comment by ldecicco-USGS** [comment]
https://blog.rstudio.org/2016/07/05/httr-1-2-0/

**Comment by ldecicco-USGS** [comment]
Is it now just:
```
returnedList <- RETRY("GET",obs_url, ..., user_agent(default_ua()))
```

**Comment by ldecicco-USGS** [comment]
I implemented this. I doesn't help with WAF issues that don't return ANYTHING. So, leaving this open to decide if we want to do something about that.
