### ISSUE TITLE
reading from WQX files?

### ISSUE THREAD

**Issue by philippi** [USGS-R/dataRetrieval#220]
Are there any plans to extend this package to work with WQX, e.g., importWQX, readWQX, whatWQXData, & whatWQXsites?
NPS WRD is migrating most (but not all) of our data from STORET to EQuIS.  NPS IMD uses restrends, EGRET, etc., for analyses & reporting.  We already pull data from WQP (e.g., USGS sites upstream or downstream for comparisons), but (allegedly) need to pull data from the NPS WRD EQuIS instance, too.
I don't like the idea of EQuIS-specific coding, as their schema will change over time.  I think that the solution is to code against their WQX (export) tables, in a way that would work for other WQX tables or files, too.

**Comment by ldecicco-USGS** [comment]
Sorry for the late (LATE) response. Just to add something to this. I did try many moons ago to write a good WQX parser, and found it to be pretty slow and difficult in R relative to the tsv output that WQP offers. I'm leaving this issue open because we do occasionally bring up adding a WQX parser. If someone wanted to contribute it, I'd be open to the idea. Currently though, we don't have the resources to do a good job on it.
