### ISSUE TITLE
National Water Use service

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#232]
http://waterdata.usgs.gov/nwis

http://waterdata.usgs.gov/nwis/wu

**Comment by ldecicco-USGS** [comment]
Might be worth taking a look:
http://help.waterdata.usgs.gov/news/061016

**Comment by wdwatkins** [comment]
#244 Adds its own function.  Could still be tied in to `readNWISdata`

**Comment by wdwatkins** [comment]
I'm thinking now there won't be much to gain as far as functionality from `readNWISdata`, since the only additional argument you can supply is a category.  The query formats and arguments are different enough from the other services that most of the `readNWISdata` code won't handle it well.  It could still be tied in, although largely as just an indirect call to `readNWIS use`.
