### ISSUE TITLE
readNWISuv for water quality, where there are two turbidity probes installed  (both which have a sublocation)

### ISSUE THREAD

**Issue by toddlester** [USGS-R/dataRetrieval#389]
Hey there,

I was trying to use readNWISuv, with the following code:

``start <- "2016-10-04"   #start date ``
``end`<-  "2017-08-14"   #end date ``
`` usgsST <- "01585075"  #station ID ``
`` TU <- as.data.frame(readNWISuv(usgsST, "63680", start, end, tz = "America/Jamaica")) ``

which returns no data, because this site apparently has ( well had, as one of the probes was removed last summer)  two different turbidity probes set at sub-locations, using the same p-code.  

the probes are set as   63680 TS032
                                     63680 TS087

anyone know of a work around for this 'rare' situation? 

Thanks!

Todd

**Comment by ldecicco-USGS** [comment]
No data at all? Maybe you need to update all your packages, because I got data. If you are using RStudio:

![update](https://user-images.githubusercontent.com/1105215/29275429-aa655182-80d0-11e7-8b00-53f786df23c5.png)

I did notice with your query I only got TS087. I checked and (according to NWIS), TS032 collects data from 09/29/2015 - 05/18/2016...so TS032 wouldn't fit in your query.

The way I checked was:
```
end<- "2017-08-14" #end date
usgsST <- "01585075" #station ID
TU_long <- as.data.frame(readNWISuv(usgsST, "63680", startDate ="", end, tz = "America/Jamaica"))
names(TU_long)
[1] "agency_cd"              "site_no"               
[3] "dateTime"               "X_TS087_63680_00000"   
[5] "X_TS087_63680_00000_cd" "X_TS032_63680_00000"   
[7] "X_TS032_63680_00000_cd" "tz_cd" 
```

**Comment by ldecicco-USGS** [comment]
Was told updating packages fixed this issue.
