### ISSUE TITLE
How to figure out `parameterCd` or `statCd` options from ?dataRetrieval::readNWISdv()

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#438]
From docs:
> `parameterCd` character of USGS parameter code(s). This is usually an 5 digit number.

and 
> `statCd` character USGS statistic code. This is usually 5 digits. Daily mean (00003) is the default.

I can find the [pcodes link](https://nwis.waterdata.usgs.gov/nwis/pmcodes/) from `?dataRetrieval::readNWISdv`, but that doc file isn't linked to this one. Not sure where to find help from dR on `statCd`. Is there a link to [statCd](https://help.waterdata.usgs.gov/stat_code) somewhere else in the help?

**Comment by ldecicco-USGS** [comment]
Unfortunately, the best tables are also the worst for server malfunctions:
https://help.waterdata.usgs.gov/codes-and-parameters
There's a ton of great info in there....but CRAN checks each link, so if it's down, I get a message to fix the links. 

The best way to get info on pCodes is to use the data frame that's included in the package:
```
library(dataRetrieval)
parameterCdFile <- parameterCdFile
```
Then, you can either search by `parameter_cd` if you are looking up the parameter code, or (what I find myself doing all the time) grep on the paramter_nm:
```
phos <- parameterCdFile[grep("phosphor",parameterCdFile$parameter_nm, ignore.case = TRUE),]
```
Also, it looks like the parameter code lookup service has been expanded a bit, so we could add some `...`'s to `readNWISpCode`....
https://nwis.waterdata.usgs.gov/nwis/pmcodes

Here's the help page link I historically had in the help files (but took out due to constant outages and ):
https://help.waterdata.usgs.gov/codes-and-parameters/parameters

Here's the stat code one by the way:
https://help.waterdata.usgs.gov/stat_cd_nm


I'm hoping to have some time this week and/or next to get to some dataRetrieval updates, I'll try to beef up the help files, and see what we can do with those additional arguments. (and add hopefully a stable valid link to the stat service codes...long ago I had tried to convince NWIS to add a stat code lookup service...I got a solid "maybe someday"...)

**Comment by ldecicco-USGS** [comment]
Just got another error on a `check` about these links, so I'm still not going to add them to the documentation.
