### ISSUE TITLE
Recently discovered bug in readWQPqw

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/dataRetrieval#453]
Use to work:

```r
rawWQP <- dataRetrieval::readWQPqw('21FLEECO_WQX-IMPRGR80','Phosphorus', '', '')
Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)
```

**Comment by ldecicco-USGS** [comment]
Well...now this query works fyi.

**Comment by ldecicco-USGS** [comment]
Still looking if I can get rid of the possibility of getting that error

**Comment by MNewcomer** [comment]
A similar problem just emerged for me:
`rawData <- dataRetrieval::readWQPqw(siteNumbers = "CEDEN-LLLR", parameterCd = "")`

**Comment by judithcthomas** [comment]
I got the same error
```
BactData <- readWQPdata(statecode="08",huc="14010005", characteristicName="Escherichia coli")
Error: Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)
```

**Comment by ldecicco-USGS** [comment]
Ugg! Sorry, I'll try to carve out some time tomorrow to get to the bottom of this!

**Comment by jbojz** [comment]
Hi there,  
As of 3/21 I'm still getting the same error.

readWQPqw('MNPCA-S001-926','Inorganic nitrogen (nitrate and nitrite)','2007-01-01','2018-01-01')
Error: Can't join on 'code' x 'ActivityEndTime/TimeZoneCode' because of incompatible types (character / logical)

Not to be a pain, I just figured I'd provide a status update from the user side.

**Comment by ldecicco-USGS** [comment]
Fixed and on it's way to CRAN
