### ISSUE TITLE
Odd time shift using readNWISuv

### ISSUE THREAD

**Issue by jbost1458** [USGS-R/dataRetrieval#474]
The following code retrieves data that is off by one hour:

dat <- readNWISuv("01201487", "00060", startDate = "2007-01-24T15:15Z", endDate = "2007-01-24T16:15Z")
View(dat)

Instead of discharge data from 15:15 - 16:15 UTC, I'm getting discharge data from 16:15 - 17:15 UTC.

I was using similar code a week or so ago with no problems...Not sure if this is an issue on my machine or are others also getting data that is shifted by one hour from what is requested in the function?

**Comment by ldecicco-USGS** [comment]
The NWIS team is investigating! You've stumped them.....I'll let you know when I hear back.

**Comment by jbost1458** [comment]
Thanks!

**Comment by ldecicco-USGS** [comment]
Unfortunately, I think it's a bug in the NWIS system. The URL for the data you are requesting is:

https://nwis.waterservices.usgs.gov/nwis/iv/?site=01201487&format=waterml,1.1&ParameterCd=00060&startDT=2007-01-24T15:15Z&endDT=2007-01-24T16:15Z

The data is correct...but you would assume you'd get data an hour earlier since January isn't in daylight savings time. I think the problem is that now that we're in standard time...the request is getting converted wrong. (I checked, if I request some data in July, fully within the standard time, it comes back as expected).

They are aware of the bug now (and consider it a bug), but I'm not sure how high a priority it is to fix, so I can't say when it might be fixed. In the meantime, I think you'd need to ask for data with an hour buffer, and filter out what you need. Let me know if you need help on that.

**Comment by jbost1458** [comment]
Ok, thanks for the prompt reply.

While investigating this bug, I have noticed that some water quality data from readNWISqw had odd time shifts. For example:
all.est <- readNWISqw("01201487", "00600", 
                  startDate = "2007-03-01", 
                  endDate = "2007-06-01")

est.edt <- readNWISqw("01201487", "00600", 
                      startDate = "2017-03-01", 
                      endDate = "2017-06-01")

View(all.est)
View(est.edt)

In all.est, I was confused as to why startDateTime values were shifted by 5 hours for samples collected both during EDT and EST. I realized that samples collected during 2007 (all.est) have "EST" recorded for sample_start_time_datum_cd_reported - which I assume is used in the conversion to UTC - both before and after daylight savings began. Data collected later, in 2017 (est.edt), have sample_start_time_datum_cd_reported as expected, "EST" prior to April, "EDT" once daylight savings time begins. Is it likely that samples collected after daylight savings time in the all.est dataframe should actually have "EDT" in the sample_start_time_datum_cd column?

Ultimately I'm attempting to pair instantaneous discharge with various water quality data across many watersheds in different time zones. So time zone codes and potential bugs are obviously important for my purpose.

**Comment by ldecicco-USGS** [comment]
It's very possible the data is correct in this case. There have been several instances I know about where sites changed how they collect their data and decided to start or stop using daylight savings. It's super frustrating. But...I would trust the sample_start_time_datum_cd. Is it possibly a human error....sure....but I know of some sites where that is intentional.
