### ISSUE TITLE
Query high and low observation within a period of record

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/dataRetrieval#538]
Users have requested the ability to query a site for a high and low observation for each pcode within a specified time frame. 

Ideally, this would allow a user to query a site (or list of sites) and ask for the highest and lowest value associated with a pcode for a specified or custom period of record.

**Comment by ldecicco-USGS** [comment]
Is this for a particular type of data? I'm not familiar with a particular web service that will do that. However, if you pull the data from the site for the period of record that you are interested, you could get the max and min values with the `range` function (in R) - or other ways depending on what you are trying to do. The exact R script to pull that info out though depends on the type of data you are getting (mostly because some tables that come back are "wide" and others are "long").

**Comment by chopkins-usgs** [comment]
I like the idea of using the range function to do so. I recommend that Charles Schalk use this function in dataRetrieval to replace his current uses in Groundwater Watch. @
