### ISSUE TITLE
Why was checkWQPdates made internal - this breaks the WQP Data Discovery Tool 

### ISSUE THREAD

**Issue by dmcglinn** [USGS-R/dataRetrieval#617]
The [WQP Data Discovery Tool](https://www.epa.gov/waterdata/water-quality-portal-data-discovery-tool) makes a call to the function `checkWQPdates` because this function was made internal in commit b8af80967 this tool no longer works. If folks aren't opposed may I suggest this function be added to exports and not treated as an internal only function. On a side note the package still provides some minimal documentation for this function.

**Comment by ldecicco-USGS** [comment]
There was a warning or note (I forget) that I was not able to figure out how to get rid of in that function (showing up on official CRAN tests). It honestly made no sense. I switched it to internal because that got rid of the warning/note. 

I just re-tested it as an exported function, and the notes/warning is gone. I'll switch it back to a public function and see if anything creeps up in the various OS testings. If it seems clean, I'll get it back up on the next CRAN release. Even at the time I thought it must have been something on their end because nothing in that function should be flag-worthy. But... it's always good to try to keep CRAN happy (I always assume they're right and I'm wrong...but that was one I was super confused about).
