### ISSUE TITLE
unify sitename arg name

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/dataRetrieval#66]
`siteNumber` vs `sites` appears in different functions. Should consider unifying this so it is easy to switch between functions and you have a expectation of the design pattern.

**Comment by ldecicco-USGS** [comment]
I *think* it's only for the 'generalized' `readNWISdata` or `readWQPdata` functions (?). That is because in those functions, the user must follow the particular web services rules. I could add a blurb in there to convert siteNumbers to sites for those specific functions (I have other similar features in there to allow R dates and stuff). 

On the otherhand, if there's an actual function argument `sites` that I missed, let me know.

**Comment by jread-usgs** [comment]
Yeah, there is a function (or two?) that use "sites" as the arg. I ran into this issue because I assumed the same syntax would be used across all functions that use site or siteNumber.

**Comment by ldecicco-USGS** [comment]
If you find it, let me know which ones. If I search "#' @param sites" in my R code, I get zero hits.

**Comment by jread-usgs** [comment]
ok, I see what you mean. It is generalized for `readNWISdata`, but not for anything else.

**Comment by ldecicco-USGS** [comment]
I'll add a conversion to those functions.

**Comment by jread-usgs** [comment]
ok, so if you pass in `siteNumbers` or `siteNumber` it converts the string to `sites`?

**Comment by ldecicco-USGS** [comment]
That will be the plan for the 'generalized' functions (`readNWISdata` and `readWQPdata`). Sound good?

**Comment by jread-usgs** [comment]
sounds good to me

**Comment by ldecicco-USGS** [comment]
In on the next pull request.
